name: Security Badges

on: push

jobs:

  count:
    permissions:
      security-events: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Alert Counts
        uses: tuckerweibell/security-badge-action@main
        with: 
          token: ${{ secrets.PAT_TOKEN }}
        
