name: Update Security Badges 

on:
  push:
    branches:
      - main
      - master

jobs:

  analyze-alerts:
    outputs:
      dependabot-count: ${{ steps.count.outputs.dependabot-alert-count }}
      code-scanning-count: ${{ steps.count.outputs.code-scanning-alert-count }}
      secret-scanning-count: ${{ steps.count.outputs.secret-scanning-alert-count }}
    permissions:
      security-events: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Alert Counts
        id: count
        uses: tuckerweibell/security-badge-action@main
        with: 
          token: ${{ secrets.PAT_TOKEN }}
        
