name: Update Security Badges 
 
on:
  push:
    branches:
      - main
      - master

jobs:

  security-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Badges
        id: one
        uses: tuckerweibell/security-badge-action@main
        with: 
          token: ${{ secrets.PAT_TOKEN }}
          gist-id: 7b75c47733bb35fe26c1a92b083047b0
          dependabot-minimum: 0
          dependabot-maximum: 15
          code-scanning-minimum: 0
          code-scanning-maximum: 100
          secret-scanning-minimum: 0
          secret-scanning-maximum: 1
          secret-scanning-enabled: true
      - name: Print 1
        run: echo ${{ steps.one.outputs.test-one }} 
      - name: Print 2
        run: echo ${{ steps.one.outputs.test-two }} 
      - name: Print 3
        run: echo ${{ steps.one.outputs.test-three }} 
       
