name: Update Security Badges 
 
on:
  push:
    branches:
      - main
      - master

jobs:

  security-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Badges
        uses: tuckerweibell/security-badge-action@main
        with: 
          token: ${{ secrets.PAT_TOKEN }}
          gist-id: 7b75c47733bb35fe26c1a92b083047b0
          dependabot-minimum: 0
          dependabot-maximum: 15
          dependabot-badge-name: 'Dependabot Bros'
          dependabot-filename: 'bros4life.json'
          code-scanning-minimum: 0
          code-scanning-maximum: 100
          code-scanning-badge-name: 'Code Scanning'
          secret-scanning-minimum: 0
          secret-scanning-maximum: 1
          secret-scanning-badge-name: 'Secret Scanning'
          secret-scanning-enabled: false
