name: Update Security Badges 

on:
  push:
    branches:
      - main
      - master

jobs:

  analyze-alerts:
    outputs:
      dependabot-count: ${{ steps.count.outputs.dependabot-alert-count }}
      code-scanning-count: ${{ steps.count.outputs.code-scanning-alert-count }}
      secret-scanning-count: ${{ steps.count.outputs.secret-scanning-alert-count }}
    permissions:
      security-events: read
    runs-on: ubuntu-latest
    steps:
      - name: Analyze Alerts
        id: analysis
        uses: tuckerweibell/security-badge-action@main
        with: 
          token: ${{ secrets.PAT_TOKEN }}
          dependabot-minimum: 0
          dependabot-maximum: 18
          dependabot-badge-name: 'Dependabot'
      
      - name: Print dependabot url
        run: echo "${{ steps.analysis.outputs.dependabot-svg-url }}"
